### ISSUE TITLE
How to add bottom line?

### ISSUE THREAD

**Issue by dreamlivemeng** [arjinmc/RecyclerViewDecoration#1]
I'm using.
mRecyclerView.addItemDecoration(new RecyclerViewItemDecoration(RecyclerViewItemDecoration.MODE_HORIZONTAL, Color.RED,1,0,0));
,but no bottom line. please,How to add bttom line?

**Comment by arjinmc** [comment]
Do you means you want show the last line  for the last item?  
If you do,remove the condition 
**   if (i != childrentCount - 1) **
from all the loop for drawling like
for(int i=0;i<childrentCount;i++) {
                  **  if (i != childrentCount - 1) {**
                        View childView = parent.getChildAt(i);
                        int myY = childView.getBottom();

                        Rect rect = new Rect(0, myY, parent.getWidth(), myY+bmp.getHeight());
                        ninePatch.draw(c, rect);
                  **  }**
                }

**Comment by dreamlivemeng** [comment]
thanks,It has been resolved.
