### ISSUE TITLE
使用这个GridLayoutManager控制布局item的宽高问题反馈

### ISSUE THREAD

**Issue by gzhulee** [arjinmc/RecyclerViewDecoration#10]
使用这个GridLayoutManager控制布局时
当只设置gridVerticalSpacing属性或marginVertical属性时，每个item的宽度和高度都是一致的
当同时设置或仅设置gridHorizontalSpacing属性或marginHorizontal属性时，都会出现第一列和最后一列的高度比中间列的高一些，同时宽度也是第一列和最后一列的比中间的列宽一些

**Comment by gzhulee** [comment]
我已经换了另外的一个插件，代码已经没了，不过设置就是按照readme中介绍的那部分写的，如下图：


使用 rvData.addItemDecoration(new RecyclerViewSpaceItemDecoration.Builder(this).margin(10).create());
使用 rvData.addItemDecoration(new RecyclerViewSpaceItemDecoration.Builder(this).marginHorizontal(10).marginVertical(10).create());
上述两种方式都会出现网格的两边放个比中间的大的情况，
我在设置网格间隔显色的时候看到具体显现是中间的格子的大小是正确的，只是格子内部的空间被上移了几个像素（所有控件的顶部是齐的），当把间隔色设成透明的时候，就是看上去中间部分的控件比两边的高度小了。
我是在android的TV界面上调试布局样式，外部还套用了其他控件，可能是有冲突吧！

使用RecyclerViewItemDecoration 这个类时也存在类似的现象

**Comment by gzhulee** [comment]
是最新的版本

**Comment by Vegen** [comment]
请问这个bug解决了吗，我也遇到同样问题，第一列会宽一些。。。。。。。。
_rv.layoutManager = GridLayoutManager(this, 4)
        _rv.addItemDecoration(RecyclerViewSpaceItemDecoration.Builder(this)
                .marginHorizontal(16f.dp2px())
                .marginVertical(16f.dp2px())
                .create())

**Comment by arjinmc** [comment]
> 这个bug浪费了我大半天时间，我觉得大佬你还是重视一下修复一下吧。。。

哈哈，不好意思啦。这个问题，我换了两次实现方案了，但是还存在这个问题。年底忙啊，来不及弄了，先改用GridView吧，后面这个分割线要结合LayoutManager来实现，目前定了这个方案。但是，短期弄出来，不太可能。

**Comment by qiushui95** [comment]
看看是不是这个解决方案
https://blog.csdn.net/u013394527/article/details/78474706

**Comment by arjinmc** [comment]
改用v4.0版本的ReyclerViewGridItemDecoration或者ReyclerViewGridSpaceItemDecoration
