### ISSUE TITLE
recyclerview高度问题

### ISSUE THREAD

**Issue by AlvinQiang** [arjinmc/RecyclerViewDecoration#3]
recyclerview添加了分割线 ，好像分隔线的高度并没有计算到recyclerview的高度里边去

**Comment by arjinmc** [comment]
是哪个分割线？如果是StickyHeadItemDecoration，暂时请停用，有个bug还没处理完。

**Comment by AngelBo** [comment]
线条的边距设置了没有效果 我是GridLayoutManager 中间的分割线距离上下边距有一定距离的 设置了没有效果

**Comment by arjinmc** [comment]
AngelBo，目前分割线没有这个功能。你可以直接在item里面设置margin就可以了。分割线pading开头和结尾部分，目前只支持线性布局的方式。更新了一下，之前网格布局有一些bug，请改用2.3.3版本。

**Comment by arjinmc** [comment]
@AngelBo 目前分割线没有这个功能。你可以直接在item里面设置margin就可以了。分割线pading开头和结尾部分，目前只支持线性布局的方式。更新了一下，之前网格布局有一些bug，请改用2.3.3版本。

**Comment by AlvinQiang** [comment]
奇怪 ，没有收到回复消息....之前问题是使用是在stickyNavLayout里边，应该跟你说的StickyHeadItemDecoration，是一个问题吧
