### ISSUE TITLE
GridLayoutManager 时计算 offset 和 draw 的不太对

### ISSUE THREAD

**Issue by NamekMaster** [arjinmc/RecyclerViewDecoration#4]
发现了 GridLayoutManager 时的2个问题，
1. 如果GridLayoutManager spanSize 是1，计算 offset 时，最右边的空白被忽略了。
2. 每行如果 item 不是正好填满的话，比如说每行四个，一共8个 item，并且thickness和 spacing设置的不一样，角落里的会错位，就现在例子， Common Style 里的，item 改少就能看出来了。

**Comment by arjinmc** [comment]
我看看，这个有可能是切换导致的。我做分组的时候也遇到这种问题，直接用是ok的。

**Comment by arjinmc** [comment]
第一个问题解决了。第二个问题不是很明白，可以给我发个图片吗？

**Comment by NamekMaster** [comment]
![image](https://user-images.githubusercontent.com/11484722/34088518-ca1478b0-e3e4-11e7-8dd1-5b7e848198dc.png)
看左下角和you'xia右下角

**Comment by arjinmc** [comment]
ok了。后面再继续优化绘制的算法。

**Comment by arjinmc** [comment]
新的绘制方案更新了，请改用2.3.3版本。感谢你给我提交bug。
