### ISSUE TITLE
thickness 这个值 能<= 2嘛 

### ISSUE THREAD

**Issue by wlingf** [arjinmc/RecyclerViewDecoration#7]
看源码  如果thickness 值<= 2，直接=2, 对于我的需求来说 这个2 有点大了，最好是这个值 想设置多少就是多少 不要添加条件

**Comment by arjinmc** [comment]
可以，这是个像素值，最小是1。只是2的倍数体验会更好。

**Comment by protectedMan** [comment]
框架中强制设置 thickness最小为2，能否放开限制，有时候需求是1像素分割线厚度
