### ISSUE TITLE
grid模式设置间隔较大时 item的宽高不等

### ISSUE THREAD

**Issue by WindyChZh** [arjinmc/RecyclerViewDecoration#8]
grid模式设置间隔较大时 item的宽高不等，间隔是相等的可是item的宽高不相等了

**Comment by arjinmc** [comment]
你怎么设置的，我看看。

**Comment by arjinmc** [comment]
你说item的高宽不相等，那个是要你在设置recyclerview item的的高宽啊，跟分割线没有直接关系喔。分割线是根据你实际item的高宽来画线。

**Comment by tiansuo** [comment]
现在依然还会有这个问题，我是在recyclerview中的每一个item里面嵌套了一个recyclerview，内部的recyclerview设置成grid格式，最后一个分割线很明显的变短了
