### ISSUE TITLE
grid模式item宽高问题

### ISSUE THREAD

**Issue by WindyChZh** [arjinmc/RecyclerViewDecoration#9]
如果间隔设置的比较大，最后一列和前面几列的宽不相同，主要是因为recyclerview宽是固定的，没个item间隔相等最后导致最后一列的item宽出现问题，设置间隔较先时不明显，但是设置比较大的时候就会很明显

**Comment by arjinmc** [comment]
哦哦，这样描述我看明白了。我跟进一下，thx。

**Comment by arjinmc** [comment]
最近有些忙。更新了2.5.3，修改了这个bug
